include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/
    - lib/core/utils/network/rest_client.g.dart
  errors:
    avoid_print: error
    prefer_single_quotes: warning
    empty_statements: error
    hash_and_equals: error
    prefer_const_constructors: error
    prefer_const_declarations: error
    always_declare_return_types: warning
    depend_on_referenced_packages: error
    file_names: error
    prefer_null_aware_method_calls: warning
    always_use_package_imports: warning
linter:
  rules:
    - no_logic_in_create_state
    - constant_identifier_names
    - camel_case_types
    - camel_case_extensions
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_spread_collections
    - unawaited_futures
    - unrelated_type_equality_checks
    - unsafe_html
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-passing-async-when-sync-expected
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-nested-conditional-expressions
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
